2021-12-26 22:49:08: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
