2021-12-26 21:35:37: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:37:11: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:39:29: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:39:54: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:39:55: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:39:56: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:39:56: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:40:33: CustomError 404: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
CustomError: The user with id a91f01b4-e9e9-4016-8c01-c91cb695e58 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:24:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
2021-12-26 21:48:13: uncaughtException: Oops!
Error: Oops!
    at Object.<anonymous> (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\app.ts:36:7)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\ts-node\src\index.ts:1371:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\ts-node\src\index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\server.ts:2:1)
2021-12-26 22:01:51: Error undefined: test
Error: test
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:12:13
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:4:12)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:11:43
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\utils\routerCatch.ts:5:5
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:112:3)
2021-12-26 22:07:49: Error undefined: test
Error: test
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:12:13
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:4:12)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:11:43
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\utils\routerCatch.ts:5:5
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:112:3)
2021-12-26 22:10:03: Error undefined: test
Error: test
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:12:13
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:4:12)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\users\user.router.ts:11:43
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\utils\routerCatch.ts:5:5
    at Layer.handle [as handle_request] (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\diman\Desktop\git\nodejs2021Q4-service\node_modules\express\lib\router\route.js:112:3)
2021-12-26 22:10:03: CustomError 404: The board with id fb625707-4b4b-40ab-8a5b-6c52ecf70ee0 was not found
CustomError: The board with id fb625707-4b4b-40ab-8a5b-6c52ecf70ee0 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:20:26
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:17:66)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.service.ts:6:43)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.router.ts:22:41
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id d1441089-efc0-484c-8100-a9463ceb5839 was not found
CustomError: The task with id d1441089-efc0-484c-8100-a9463ceb5839 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id 76b0d798-a862-49d7-bce2-424966ceb1af was not found
CustomError: The task with id 76b0d798-a862-49d7-bce2-424966ceb1af was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id 36561dbb-fb03-4b9f-990d-c27bfdf0753d was not found
CustomError: The task with id 36561dbb-fb03-4b9f-990d-c27bfdf0753d was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id 05345852-80e5-493d-8747-0e5ed66003d3 was not found
CustomError: The task with id 05345852-80e5-493d-8747-0e5ed66003d3 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id e7a476d9-efa8-4d89-b72d-6ddbe9cc1641 was not found
CustomError: The task with id e7a476d9-efa8-4d89-b72d-6ddbe9cc1641 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:03: CustomError 404: The task with id 05f1e82f-9add-4fb2-a5fe-826d9c6ad3ad was not found
CustomError: The task with id 05f1e82f-9add-4fb2-a5fe-826d9c6ad3ad was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The board with id b5c55337-c14b-4b13-8059-d947898876d5 was not found
CustomError: The board with id b5c55337-c14b-4b13-8059-d947898876d5 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:20:26
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.memory.repository.ts:17:66)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.service.ts:6:43)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.router.ts:22:41
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\boards\board.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 7b508a57-66e9-40cf-9e39-545020952cb8 was not found
CustomError: The task with id 7b508a57-66e9-40cf-9e39-545020952cb8 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 2a0bf4a1-f4bb-4132-8ad7-151f4721bf1f was not found
CustomError: The task with id 2a0bf4a1-f4bb-4132-8ad7-151f4721bf1f was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 7f788d55-dc80-44da-81f1-dfa3bdeeda52 was not found
CustomError: The task with id 7f788d55-dc80-44da-81f1-dfa3bdeeda52 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 0a6ef0cf-01cd-4769-8a5b-8dc225391dd9 was not found
CustomError: The task with id 0a6ef0cf-01cd-4769-8a5b-8dc225391dd9 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 5e13674f-95ca-4b9d-b421-a705ab362ca3 was not found
CustomError: The task with id 5e13674f-95ca-4b9d-b421-a705ab362ca3 was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
2021-12-26 22:10:42: CustomError 404: The task with id 96246650-f132-4662-bb88-aeca431b6eec was not found
CustomError: The task with id 96246650-f132-4662-bb88-aeca431b6eec was not found
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:20:25
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:4:12)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.memory.repository.ts:17:65)
    at Object.getOne (C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.service.ts:6:42)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:25:39
    at Generator.next (<anonymous>)
    at C:\Users\diman\Desktop\git\nodejs2021Q4-service\src\resources\tasks\task.router.ts:8:71
